
var symbols = {
    0:"NULL",
    1:"SOH",//(Start of Header)
    2:"STX",//(Start of Text)
    3:"ETX",//(End of Text)
    4:"EOT",//(End of Trans.)
    5:"ENQ",//(Enquiry)
    6:"ACK",//(Acknowledgement)
    7:"BEL",//(Bell)
    8:"BS",//(Backspace)
    9:"HT",//(Horizontal Tab)
    10:"LF",//(Line feed)
    11:"VT",//(Vertical Tab)
    12:"FF",//(Form feed)
    13:"CR",//(Carriage return)
    14:"SO",//(Shift Out)
    15:"SI",//(Shift In)
    16:"DLE",//(Data link escape)
    17:"DC1",//(Device control 1)
    18:"DC2",//(Device control 2)
    19:"DC3",//(Device control 3)
    20:"DC4",//(Device control 4)
    21:"NAK",//(Negative acknowl.)
    22:"SYN",//(Synchronous idle)
    23:"ETB",//(End of trans. block)
    24:"CAN",//(Cancel)
    25:"EM",//(End of medium)
    26:"SUB",//(Substitute)
    27:"ESC",//(Escape)
    28:"FS",//(File separator)
    29:"GS",//(Group separator)
    30:"RS",//(Record separator)
    31:"US",//(Unit separator)
    127:"DEL"//(Delete)
};
